-- LearnU Database Architecture Phase 8: Segregation
-- **CRITICAL**: Drop existing tables to refresh foreign key networks!
-- DROP TABLE IF EXISTS public.results CASCADE;
-- DROP TABLE IF EXISTS public.questions CASCADE;
-- DROP TABLE IF EXISTS public.tests CASCADE;
-- DROP TABLE IF EXISTS public.users CASCADE;

-- Teachers Table
CREATE TABLE public.teachers (
    id UUID DEFAULT auth.uid() PRIMARY KEY,
    name TEXT NOT NULL,
    email TEXT UNIQUE NOT NULL,
    mobile TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Students Table
CREATE TABLE public.students (
    id UUID DEFAULT auth.uid() PRIMARY KEY,
    name TEXT NOT NULL,
    email TEXT UNIQUE NOT NULL,
    mobile TEXT,
    coupon_key TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Tests Table
CREATE TABLE public.tests (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    test_name TEXT NOT NULL,
    time_limit INTEGER DEFAULT 60,
    created_by UUID REFERENCES public.teachers(id) ON DELETE CASCADE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Questions Table
CREATE TABLE public.questions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    test_id BIGINT REFERENCES public.tests(id) ON DELETE CASCADE,
    question TEXT NOT NULL,
    question_type TEXT DEFAULT 'standard',
    option1 TEXT NOT NULL,
    option2 TEXT NOT NULL,
    option3 TEXT NOT NULL,
    option4 TEXT NOT NULL,
    correct_answer TEXT NOT NULL,
    extended_data JSONB, 
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Results Table
CREATE TABLE public.results (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID REFERENCES public.students(id) ON DELETE CASCADE,
    test_id BIGINT REFERENCES public.tests(id) ON DELETE CASCADE,
    score INTEGER NOT NULL,
    date TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Row Level Security
ALTER TABLE public.teachers ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.students ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.tests ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.questions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.results ENABLE ROW LEVEL SECURITY;

-- Minimal policies allowing open read/write
CREATE POLICY "Enable all for dev_teachers" ON public.teachers FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Enable all for dev_students" ON public.students FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Enable all for dev_tests" ON public.tests FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Enable all for dev_questions" ON public.questions FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Enable all for dev_results" ON public.results FOR ALL USING (true) WITH CHECK (true);
