-- Users Table
CREATE TABLE public.users (
    id UUID DEFAULT auth.uid() PRIMARY KEY,
    name TEXT NOT NULL,
    email TEXT UNIQUE NOT NULL,
    role TEXT CHECK(role IN ('teacher', 'student')) DEFAULT 'student',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Tests Table
CREATE TABLE public.tests (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    test_name TEXT NOT NULL,
    created_by UUID REFERENCES public.users(id) ON DELETE CASCADE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Questions Table
CREATE TABLE public.questions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    test_id BIGINT REFERENCES public.tests(id) ON DELETE CASCADE,
    question TEXT NOT NULL,
    question_type TEXT DEFAULT 'standard',
    option1 TEXT NOT NULL,
    option2 TEXT NOT NULL,
    option3 TEXT NOT NULL,
    option4 TEXT NOT NULL,
    correct_answer TEXT NOT NULL,
    extended_data JSONB, -- Added to support list matching formats
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Results Table
CREATE TABLE public.results (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID REFERENCES public.users(id) ON DELETE CASCADE,
    test_id BIGINT REFERENCES public.tests(id) ON DELETE CASCADE,
    score INTEGER NOT NULL,
    date TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Enable Row Level Security (Safety best practice)
ALTER TABLE public.users ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.tests ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.questions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.results ENABLE ROW LEVEL SECURITY;

-- Create minimal policies allowing everyone to read and write (for development)
CREATE POLICY "Enable all for development" ON public.users FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Enable all for development" ON public.tests FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Enable all for development" ON public.questions FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Enable all for development" ON public.results FOR ALL USING (true) WITH CHECK (true);
